# Generated by Django 2.2.4 on 2019-09-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_remove_documenttemplate_definition_hash'),
        ('ojs', '0002_remove_submission_file_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='templates',
            field=models.ManyToManyField(to='document.DocumentTemplate'),
        ),
    ]
