# Generated by Django 3.2.13 on 2022-08-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ojs", "0006_contributors_replaces_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="contributors",
        ),
        migrations.AddField(
            model_name="submissionrevision",
            name="contributors",
            field=models.JSONField(default=dict),
        ),
    ]
