# Generated by Django 3.2.13 on 2022-08-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ojs", "0007_move_contributors_from_submission_to_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewer",
            name="method",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("anonymous", "Anonymous"),
                    ("doubleanonymous", "Double anonymous"),
                ],
                default="doubleanonymous",
                max_length=15,
            ),
        ),
    ]
